FROM php:8.2.0-fpm

RUN apt-get update && apt-get install -y \
    zlib1g-dev \
    libzip-dev \
    unzip

RUN rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install zip

COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN composer self-update

WORKDIR /var/www

COPY composer.json composer.lock ./

RUN composer install

COPY ./ ./
